### ISSUE TITLE
Segmentation fault - invalid memory reference, while running routing model

### ISSUE THREAD

**Issue by LSRathore** [UW-Hydro/VIC_Routing#2]
I'm trying to run the routing model in windows using cygwin for my area. It gives a segmentation fault.  The error is as follows:

` $ ./rout global_rout_alt.txt`
` NDAY =        14092  NMONTHS =          463
 1  KolDam                 77  49
 Routing station: KolDam`
 `searching catchment...`
 `Number of grid cells upstream of present station       21334`
 `reading grid_UH...`
` making grid UH...`
` making UH_S grid...it takes a while...`
` NOTE:  your new UH_S grid file will be written in the`
        `directory you run from, and will be called`
             `KolDa.uh_s`
       `save this file and specify it in your station`
       ` location file to avoid this step in the future`
 `grid cell           1  out of       21334`

`Program received signal SIGSEGV: Segmentation fault - invalid memory reference.`

`Backtrace for this error:`
`#0  0xffffffffffffffff in ???`
`#1  0xffffffffffffffff in ???`
`#2  0xffffffffffffffff in ???`
`#3  0xffffffffffffffff in ???`
`#4  0xffffffffffffffff in ???`
`#5  0xffffffffffffffff in ???`
`#6  0xffffffffffffffff in ???`
`#7  0xffffffffffffffff in ???`
`#8  0xffffffffffffffff in ???`
`#9  0xffffffffffffffff in ???`
`#10  0xffffffffffffffff in ???`
`#11  0xffffffffffffffff in ???`
`#12  0xffffffffffffffff in ???`
`#13  0xffffffffffffffff in ???`
`#14  0xffffffffffffffff in ???`
`Segmentation fault (core dumped)`

cc @jhamman

**Comment by LSRathore** [comment]
Solved by editing rout.f file. Just increase the limit of PMAX
